# Generated by Django 6.0.7 on 2026-07-26 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('custom_id', models.CharField(max_length=20)),
                ('operation_type', models.CharField(max_length=5)),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('organization', 'Corporativo / Empresa Matriz'), ('branch', 'Sucursal / Franquicia')], max_length=20, verbose_name='Tipo')),
                ('subdomain', models.CharField(max_length=50, unique=True, verbose_name='Subdominio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Facturación')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=50, verbose_name='Plan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warehouse.tenant', verbose_name='Tenant Padre')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('storage_used_gb', models.FloatField(default=0, verbose_name='Almacenamiento usado (GB)')),
                ('operations_count', models.IntegerField(default=0, verbose_name='Número de Operaciones')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Facturación')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=50, verbose_name='Plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='warehouse.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['tenant__name'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHIPPER', 'Shipper'), ('CARRIER', 'Carrier'), ('BUNDLE_TYPE', 'Type of Bundle'), ('TYPE_OP', 'Type of Operation'), ('CC_EMAIL', 'CC Email')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, help_text='Abreviatura del cliente (ej: LBO, ACME)', max_length=50, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='+521XXXXXXXXXX', max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='warehouse.tenant')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('staff', 'Staff'), ('customer', 'Cliente')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='warehouse.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('operation_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('entry_dispatched', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_name_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_name_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('po_order', models.CharField(blank=True, max_length=200, null=True)),
                ('seal', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_name_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('pro', models.CharField(blank=True, max_length=200, null=True)),
                ('trailer', models.CharField(blank=True, max_length=200, null=True)),
                ('bundle_type_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('bundle_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Notes added by the customer', null=True)),
                ('damage', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ref_aa', models.CharField(blank=True, help_text='Referencia AA - no obligatorio', max_length=100, null=True, verbose_name='REF AA')),
                ('ref_dys', models.CharField(blank=True, help_text='Referencia DYS - no obligatorio', max_length=100, null=True, verbose_name='DYS')),
                ('pedimento', models.CharField(blank=True, help_text='Número de pedimento - no obligatorio', max_length=100, null=True, verbose_name='PED')),
                ('bundle_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'BUNDLE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_bundle_type', to='warehouse.catalog')),
                ('carrier', models.ForeignKey(blank=True, limit_choices_to={'category': 'CARRIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_carrier', to='warehouse.catalog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'category': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_customer', to='warehouse.catalog')),
                ('shipper', models.ForeignKey(blank=True, limit_choices_to={'category': 'SHIPPER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_shipper', to='warehouse.catalog')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='warehouse.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(upload_to='operations/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('digital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.tenant')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.warehouseoperation')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Rol')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_roles', to='warehouse.role', verbose_name='Rol Padre')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='warehouse.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'unique_together': {('name', 'tenant')},
            },
        ),
    ]
