# Generated by Django 5.0.4 on 2026-04-15 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHIPPER', 'Shipper'), ('CARRIER', 'Carrier'), ('BUNDLE_TYPE', 'Type of Bundle'), ('TYPE_OP', 'Type of Operation'), ('CC_EMAIL', 'CC Email')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='+521XXXXXXXXXX — WhatsApp number for notifications', max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('home', 'Home (full access)'), ('customer', 'Customer (limited access)')], default='home', max_length=20)),
                ('plain_password', models.CharField(blank=True, help_text='Stored for admin reference only', max_length=128, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to Customer catalog entry (for customer role)', limit_choices_to={'category': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.catalog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('operation_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('entry_dispatched', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_name_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('shipper_name_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('po_order', models.CharField(blank=True, max_length=200, null=True)),
                ('seal', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_name_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('pro', models.CharField(blank=True, max_length=200, null=True)),
                ('trailer', models.CharField(blank=True, max_length=200, null=True)),
                ('bundle_type_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('bundle_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('damage', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('bundle_type', models.ForeignKey(blank=True, limit_choices_to={'category': 'BUNDLE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_bundle_type', to='warehouse.catalog')),
                ('carrier', models.ForeignKey(blank=True, limit_choices_to={'category': 'CARRIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_carrier', to='warehouse.catalog')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'category': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_customer', to='warehouse.catalog')),
                ('shipper', models.ForeignKey(blank=True, limit_choices_to={'category': 'SHIPPER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_shipper', to='warehouse.catalog')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(upload_to='operations/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('digital_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.warehouseoperation')),
            ],
        ),
    ]
