# Generated by Django 6.0.7 on 2026-07-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.catalog'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delete_password',
            field=models.CharField(blank=True, help_text='Custom password required to delete records', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
