# Generated by Django 5.0.4 on 2026-04-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_v27'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='+521XXXXXXXXXX', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deletionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.catalog'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='delete_password',
            field=models.CharField(blank=True, help_text='Custom password required to delete records', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseoperation',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notes added by the customer', null=True),
        ),
    ]
