# Generated by Django 5.0.14 on 2026-06-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_alter_catalog_whatsapp_alter_deletionlog_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseoperation",
            name="pedimento",
            field=models.CharField(
                blank=True,
                help_text="Número de pedimento - no obligatorio",
                max_length=100,
                null=True,
                verbose_name="PED",
            ),
        ),
        migrations.AddField(
            model_name="warehouseoperation",
            name="ref_aa",
            field=models.CharField(
                blank=True,
                help_text="Referencia AA - no obligatorio",
                max_length=100,
                null=True,
                verbose_name="REF AA",
            ),
        ),
        migrations.AddField(
            model_name="warehouseoperation",
            name="ref_dys",
            field=models.CharField(
                blank=True,
                help_text="Referencia DYS - no obligatorio",
                max_length=100,
                null=True,
                verbose_name="DYS",
            ),
        ),
    ]
