# Generated by Django 5.0.14 on 2026-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_warehouseoperation_pedimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="Abreviatura del cliente (ej: LBO, ACME)",
                max_length=10,
                null=True,
            ),
        ),
    ]
