# Generated by Django 6.0.7 on 2026-08-04 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_default_tenant_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_logs', to='warehouse.tenant'),
        ),
    ]
