# Generated by Django 6.0.7 on 2026-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_catalog_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Abreviatura del cliente (ej: LBO, ACME)', max_length=50, null=True),
        ),
    ]
