# Generated by Django 6.0.7 on 2026-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_backfill_catalog_operations_documents_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['tenant__name'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_email',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='config',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
