# Generated by Django 6.0.7 on 2026-08-17 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_backfill_deletionlog_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Notificar por email'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='notify_on_create',
            field=models.BooleanField(default=True, verbose_name='Avisar al registrar la operacion'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='notify_on_documents',
            field=models.BooleanField(default=False, verbose_name='Avisar al agregar documentos'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='notify_on_release',
            field=models.BooleanField(default=False, verbose_name='Avisar al liberar la mercancia'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='notify_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Notificar por WhatsApp'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_custom_id', models.CharField(blank=True, max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=10)),
                ('event', models.CharField(choices=[('OPERATION_CREATED', 'Operación registrada'), ('GOODS_RELEASED', 'Mercancía liberada'), ('DOCUMENTS_ADDED', 'Documentos agregados'), ('MANUAL', 'Envío manual')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Enviada'), ('FAILED', 'Fallida'), ('SKIPPED', 'Omitida')], max_length=10)),
                ('recipient', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'category': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='warehouse.catalog')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='warehouse.warehouseoperation')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='warehouse.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='warehouse_n_tenant__2d1677_idx'), models.Index(fields=['operation'], name='warehouse_n_operati_56ab70_idx')],
            },
        ),
    ]
