# Generated by Django 6.0.7 on 2026-08-18 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_notificationlog_and_catalog_notify_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=6)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='warehouse.tenant')),
            ],
            options={
                'verbose_name': 'Consecutivo de documentos',
                'verbose_name_plural': 'Consecutivos de documentos',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day'), name='unique_document_sequence_per_day')],
            },
        ),
    ]
