# Generated by Django 6.0.7 on 2026-08-18 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_documentsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador de plataforma'), ('staff', 'Soporte de plataforma')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de plataforma',
                'verbose_name_plural': 'Usuarios de plataforma',
                'ordering': ['user__username'],
            },
        ),
    ]
