# Generated by Django 6.0.7 on 2026-08-19 04:49

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_platformuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationdocument',
            options={'base_manager_name': 'todos'},
        ),
        migrations.AlterModelManagers(
            name='operationdocument',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='deletionlog',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deletionlog',
            name='kind',
            field=models.CharField(choices=[('OPERATION', 'Operacion'), ('DOCUMENT', 'Documento')], default='OPERATION', max_length=10),
        ),
        migrations.AddField(
            model_name='operationdocument',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operationdocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_borrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletionlog',
            name='operation_type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
