"""
Retira `UserProfile.plain_password`, la contrasena de acceso en claro.

El perfil guardaba una copia legible de la contrasena de cada usuario con un
unico proposito: que la pantalla de gestion de usuarios pudiera repintarla en su
columna, para que el administrador la consultara cuando alguien la olvidara. El
precio era tener todas las contrasenas de la empresa a la vista de cualquiera
que abriera esa tabla o esa columna de la base, y ese precio no lo paga ninguna
comodidad.

La 0014 hizo lo propio con la contrasena de borrado, que se cifro porque
autoriza una accion. Con esta se cierra el caso: en la base ya no queda ninguna
contrasena legible. La de Django siempre estuvo cifrada y sigue igual, de modo
que nadie pierde el acceso; lo que se pierde es la posibilidad de consultarla.

De ida y sin vuelta: la columna se destruye con su contenido. Quien olvide su
contrasena recibe una nueva desde la misma pantalla, que es como debio ser
siempre.
"""
# Generated by Django 6.0.7 on 2026-08-20 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_cifrar_delete_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plain_password',
        ),
    ]
