# Generated by Django 6.0.7 on 2026-08-22 05:03

import warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_superusuarios_con_rol_propio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=warehouse.models.ruta_documento),
        ),
    ]
