# Generated by Django 6.0.7 on 2026-08-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_operationdocument_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationdocument',
            options={'base_manager_name': 'todos', 'ordering': ['uploaded_at', 'pk']},
        ),
    ]
