# Generated by Django 6.0.7 on 2026-08-23 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_alter_operationdocument_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consecutivo de facturas',
                'verbose_name_plural': 'Consecutivos de facturas',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('periodo_inicio', models.DateField(verbose_name='Periodo desde')),
                ('periodo_fin', models.DateField(verbose_name='Periodo hasta')),
                ('emitida_el', models.DateField(verbose_name='Emitida el')),
                ('vence_el', models.DateField(verbose_name='Vence el')),
                ('plan', models.CharField(blank=True, max_length=50, verbose_name='Plan facturado')),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (USD)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12, verbose_name='Estado')),
                ('pagada_el', models.DateField(blank=True, null=True, verbose_name='Pagada el')),
                ('referencia_de_pago', models.CharField(blank=True, max_length=120, verbose_name='Referencia de pago')),
                ('cancelada_el', models.DateField(blank=True, null=True, verbose_name='Cancelada el')),
                ('motivo_de_cancelacion', models.TextField(blank=True, verbose_name='Motivo de cancelación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='warehouse.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-emitida_el', '-numero'],
            },
        ),
    ]
