# Generated by Django 6.0.7 on 2026-08-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_invoicesequence_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationdocument',
            options={'base_manager_name': 'todos', 'ordering': ['orden', 'uploaded_at', 'pk']},
        ),
        migrations.AddField(
            model_name='operationdocument',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
