# Generated by Django 6.0.7 on 2026-08-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_alter_operationdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enviada_el',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviada el'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('OPERATION_CREATED', 'Operación registrada'), ('GOODS_RELEASED', 'Mercancía liberada'), ('DOCUMENTS_ADDED', 'Documentos agregados'), ('MANUAL', 'Envío manual'), ('INVOICE_SENT', 'Factura enviada')], max_length=20),
        ),
    ]
