# Generated by Django 6.0.7 on 2026-08-23 03:36

import warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_invoice_enviada_el_alter_notificationlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=warehouse.models.ruta_logo, verbose_name='Logo'),
        ),
    ]
