# Generated by Django 6.0.7 on 2026-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_conversation_conversationread_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('OPERATION_CREATED', 'Operación registrada'), ('GOODS_RELEASED', 'Mercancía liberada'), ('DOCUMENTS_ADDED', 'Documentos agregados'), ('MANUAL', 'Envío manual'), ('INVOICE_SENT', 'Factura enviada'), ('CHAT_MESSAGE', 'Mensaje en el hilo')], max_length=20),
        ),
    ]
