# Generated by Django 6.0.7 on 2026-08-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_alter_notificationlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdocument',
            name='mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='warehouse.message'),
        ),
    ]
