# Generated by Django 6.0.7 on 2026-08-28 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_operationdocument_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='alert_days',
            field=models.PositiveIntegerField(blank=True, help_text='Vacio = usar el plazo general de la empresa', null=True, verbose_name='Dias en bodega antes de avisar'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='alert_days_default',
            field=models.PositiveIntegerField(default=7, verbose_name='Dias en bodega antes de avisar'),
        ),
        migrations.AlterField(
            model_name='warehouseoperation',
            name='operation_type',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('TD', 'Transfer'), ('RD', 'Relocation')], max_length=5),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zona')),
                ('aisle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasillo')),
                ('rack', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estante')),
                ('level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nivel')),
                ('position', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posicion')),
                ('kind', models.CharField(choices=[('STORAGE', 'Almacenaje'), ('RECEIVING', 'Recepcion'), ('SHIPPING', 'Embarque'), ('STAGING', 'Anden / Preparacion'), ('PICKING', 'Picking'), ('QUARANTINE', 'Cuarentena'), ('DAMAGED', 'Mercancia danada'), ('RETURNS', 'Devoluciones')], default='STORAGE', max_length=12, verbose_name='Tipo de ubicacion')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='Codigo')),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.tenant')),
            ],
            options={
                'ordering': ['warehouse__code', 'zone', 'aisle', 'rack', 'level', 'position'],
            },
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='warehouse.location', verbose_name='Ubicacion'),
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_desde', to='warehouse.location', verbose_name='Ubicacion anterior'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Corto, sale en el codigo de la ubicacion (ej. LRD)', max_length=10, verbose_name='Codigo')),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='warehouse.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.warehouse', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='warehouse.warehouse', verbose_name='Bodega'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'code')},
        ),
    ]
