# Generated by Django 6.0.7 on 2026-08-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_catalog_alert_days_tenant_alert_days_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseoperation',
            name='location_from',
        ),
        migrations.AlterField(
            model_name='warehouseoperation',
            name='operation_type',
            field=models.CharField(choices=[('ENTRY', 'Entry (ED)'), ('EXIT', 'Exit (SD)'), ('TD', 'Transfer (TD)'), ('RD', 'Revision (RD)')], max_length=5),
        ),
    ]
