# Generated by Django 6.0.7 on 2026-08-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_remove_warehouseoperation_location_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Automatico'), ('es', 'Espanol'), ('en', 'English')], default='', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'Sistema'), ('light', 'Claro'), ('dark', 'Oscuro')], default='', max_length=10, verbose_name='Tema'),
        ),
    ]
