# Generated by Django 6.0.7 on 2026-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_userprofile_language_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='kind',
            field=models.CharField(choices=[('STORAGE', 'Storage'), ('RECEIVING', 'Receiving'), ('SHIPPING', 'Shipping'), ('STAGING', 'Dock / Staging'), ('PICKING', 'Picking'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged goods'), ('RETURNS', 'Returns')], default='STORAGE', max_length=12, verbose_name='Tipo de ubicacion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Automatic'), ('es', 'Espanol'), ('en', 'English')], default='', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(blank=True, choices=[('', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='', max_length=10, verbose_name='Tema'),
        ),
    ]
