# Generated by Django 6.0.7 on 2026-08-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_alter_location_kind_alter_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Platform administrator'), ('staff', 'Platform support')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super administrator'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
