# Generated by Django 6.0.7 on 2026-08-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_alter_platformuser_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('es', 'Espanol'), ('en', 'English')], default='', max_length=5, verbose_name='Idioma de los correos y documentos'),
        ),
    ]
