# Generated by Django 6.0.7 on 2026-08-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_catalog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('es', 'Español'), ('en', 'English')], default='', max_length=5, verbose_name='Idioma de los correos y documentos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Automatic'), ('es', 'Español'), ('en', 'English')], default='', max_length=5, verbose_name='Idioma'),
        ),
    ]
