# Generated by Django 6.0.7 on 2026-08-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_alter_catalog_language_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionlog',
            name='kind',
            field=models.CharField(choices=[('OPERATION', 'Operation'), ('DOCUMENT', 'Document')], default='OPERATION', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('OPERATION_CREATED', 'Operation registered'), ('GOODS_RELEASED', 'Goods released'), ('DOCUMENTS_ADDED', 'Documents added'), ('MANUAL', 'Manual send'), ('INVOICE_SENT', 'Invoice sent'), ('CHAT_MESSAGE', 'Message in the thread')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=10),
        ),
    ]
