# Generated by Django 6.0.7 on 2026-09-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_alter_deletionlog_kind_alter_notificationlog_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseoperation',
            name='eta',
            field=models.DateField(blank=True, help_text='Fecha estimada de llegada', null=True, verbose_name='ETA'),
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='has_serial_numbers',
            field=models.BooleanField(default=False, verbose_name='Esta mercancia tiene numeros de serie'),
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='ped_aduana',
            field=models.CharField(blank=True, default='', help_text='2 digitos. 24 = Nuevo Laredo, 80 = Colombia', max_length=2, verbose_name='Aduana de despacho'),
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='ped_consecutivo',
            field=models.CharField(blank=True, default='', help_text='7 digitos: el ultimo digito del ano mas el consecutivo', max_length=7, verbose_name='Ano y consecutivo'),
        ),
        migrations.AddField(
            model_name='warehouseoperation',
            name='ped_patente',
            field=models.CharField(blank=True, default='', help_text='4 digitos', max_length=4, verbose_name='Patente del agente aduanal'),
        ),
        migrations.CreateModel(
            name='Pedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Numero provisional')),
                ('ped_aduana', models.CharField(blank=True, default='', max_length=2, verbose_name='Aduana de despacho')),
                ('ped_patente', models.CharField(blank=True, default='', max_length=4, verbose_name='Patente del agente aduanal')),
                ('ped_consecutivo', models.CharField(blank=True, default='', max_length=7, verbose_name='Ano y consecutivo')),
                ('anio_validacion', models.CharField(blank=True, default='', max_length=2, verbose_name='Ano de validacion')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Draft'), ('EN_REVISION', 'Under customer review'), ('CORRECCIONES', 'Corrections requested'), ('APROBADO', 'Approved by the customer'), ('VALIDADO', 'Validated'), ('PAGADO', 'Paid')], default='BORRADOR', max_length=15)),
                ('enviado_a_revision_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('correcciones_pedidas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedimentos_creados', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'category': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedimentos', to='warehouse.catalog', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='warehouse.tenant')),
            ],
            options={
                'verbose_name': 'Pedimento',
                'verbose_name_plural': 'Pedimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedimentoBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bultos', models.PositiveIntegerField(default=1, verbose_name='Bultos que van a este pedimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones_de_pedimento', to='warehouse.warehouseoperation')),
                ('pedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='warehouse.pedimento')),
            ],
            options={
                'verbose_name': 'Reparto de bultos',
                'verbose_name_plural': 'Reparto de bultos',
                'ordering': ['operation__custom_id'],
                'unique_together': {('pedimento', 'operation')},
            },
        ),
    ]
