# Generated by Django 6.0.7 on 2026-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_warehouseoperation_eta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedimentobundle',
            name='weight_kgs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilos de estos bultos'),
        ),
        migrations.AddField(
            model_name='pedimentobundle',
            name='weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Libras de estos bultos'),
        ),
    ]
