# Generated by Django 6.0.7 on 2026-09-07 17:35

import django.db.models.deletion
import warehouse.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_pedimentobundle_weight_kgs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdocument',
            name='ranura',
            field=models.CharField(blank=True, choices=[('', 'No particular role'), ('FACTURA_COMERCIAL', 'Commercial invoice')], default='', max_length=30, verbose_name='Papel dentro del expediente'),
        ),
        migrations.CreateModel(
            name='PedimentoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranura', models.CharField(choices=[('M3', 'M3 file'), ('PROFORMA', 'Pedimento draft'), ('COVE', 'COVE'), ('CARTA_318', '318 letter'), ('FOTOS_SERIES', 'Serial-number photos'), ('OTROS', 'Other'), ('MANIFESTACION', 'Statement of value'), ('ACUSE', 'Statement of value receipt'), ('PEDIMENTO_PAGADO', 'Paid pedimento'), ('SHIPPER', 'Shipper')], max_length=20)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=warehouse.models.ruta_documento)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('documento_de_operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usos_en_pedimentos', to='warehouse.operationdocument')),
                ('pedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='warehouse.pedimento')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_de_pedimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del pedimento',
                'verbose_name_plural': 'Documentos del pedimento',
                'ordering': ['ranura', 'uploaded_at'],
            },
        ),
    ]
