# Generated by Django 6.0.7 on 2026-09-07 18:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0036_operationdocument_ranura_pedimentodocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosDeImpuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate, verbose_name='Vigente desde')),
                ('tipo_de_cambio', models.DecimalField(decimal_places=4, default=Decimal('19.0000'), max_digits=10, verbose_name='Tipo de cambio de trabajo')),
                ('prevalidacion', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10, verbose_name='Cuota de prevalidacion (MXN)')),
                ('dta_sin_tmec', models.DecimalField(decimal_places=6, default=Decimal('0.008'), max_digits=8, verbose_name='Tasa del DTA sin T-MEC')),
                ('dta_con_tmec', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8, verbose_name='Tasa del DTA con T-MEC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametros_creados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_de_impuestos', to='warehouse.tenant')),
            ],
            options={
                'verbose_name': 'Parametros de impuestos',
                'verbose_name_plural': 'Parametros de impuestos',
                'ordering': ['-vigente_desde', '-created_at'],
            },
        ),
    ]
