# Generated by Django 6.0.7 on 2026-09-07 18:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_parametrosdeimpuestos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenglonDeImpuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_order', models.CharField(blank=True, default='', max_length=200, verbose_name='Pedido')),
                ('guia', models.CharField(blank=True, default='', max_length=200)),
                ('eta', models.DateField(blank=True, null=True)),
                ('valor_expresion', models.CharField(blank=True, default='', max_length=60, verbose_name='Valor tal como se tecleo')),
                ('valor_mercancia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de mercancia USD')),
                ('fletes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('incrementables', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tasa_igi', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='Tasa de IGI')),
                ('aplica_tmec', models.BooleanField(default=False, verbose_name='Aplica el T-MEC')),
                ('impuesto_reportado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Impuesto reportado MXN')),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, limit_choices_to={'category': 'CARRIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renglones_como_carrier', to='warehouse.catalog')),
                ('customer', models.ForeignKey(limit_choices_to={'category': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='renglones_de_impuestos', to='warehouse.catalog', verbose_name='Cliente')),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renglon_de_impuestos', to='warehouse.warehouseoperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones_de_impuestos', to='warehouse.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renglones_tocados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renglon de la hoja de impuestos',
                'verbose_name_plural': 'Renglones de la hoja de impuestos',
                'ordering': ['-created_at'],
            },
        ),
    ]
