# Generated by Django 6.0.7 on 2026-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_renglondeimpuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(blank=True, default='', help_text='Como aparece en la hoja de impuestos. Vacio = se recorta el nombre.', max_length=20, verbose_name='Nombre corto'),
        ),
    ]
