# Generated by Django 6.0.7 on 2026-09-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_tenant_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_de_cruce', models.DateField(verbose_name='Dia de cruce')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Open'), ('CON_ORDEN', 'Load order issued'), ('CARGADA', 'Loaded'), ('CRUZADA', 'Crossed'), ('CANCELADA', 'Cancelled')], default='ABIERTA', max_length=12)),
                ('origen', models.CharField(choices=[('CLIENTE', 'Created by the customer'), ('TENANT', 'Created by the warehouse on their behalf')], default='CLIENTE', max_length=10)),
                ('confirmada_por_el_cliente', models.BooleanField(default=False)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruces_creados', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'category': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='cruces', to='warehouse.catalog', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces', to='warehouse.tenant')),
            ],
            options={
                'verbose_name': 'Tarea de cruce',
                'verbose_name_plural': 'Tareas de cruce',
                'ordering': ['fecha_de_cruce', 'custom_id'],
            },
        ),
        migrations.CreateModel(
            name='CambioDeDiaDeCruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField()),
                ('fecha_nueva', models.DateField()),
                ('motivo', models.CharField(choices=[('TIPO_DE_CAMBIO', 'Exchange rate'), ('TRANSPORTE', 'Transport'), ('ADUANA', 'Customs system down'), ('CLIENTE', 'The customer asked'), ('OTRO', 'Other')], max_length=20)),
                ('detalle', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_de_dia', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_de_dia', to='warehouse.crossingtask')),
            ],
            options={
                'verbose_name': 'Cambio de dia de cruce',
                'verbose_name_plural': 'Cambios de dia de cruce',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossingTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.CharField(choices=[('OPERACIONES', 'From the operations list'), ('IMPUESTOS', 'From the duty sheet'), ('TAREA', 'From the crossing task')], default='TAREA', max_length=12)),
                ('motivo', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarques_metidos', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces', to='warehouse.warehouseoperation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='warehouse.crossingtask')),
            ],
            options={
                'verbose_name': 'Embarque de la tarea',
                'verbose_name_plural': 'Embarques de la tarea',
                'ordering': ['added_at'],
                'unique_together': {('task', 'operation')},
            },
        ),
    ]
