# Generated by Django 6.0.7 on 2026-09-07 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0040_crossingtask_cambiodediadecruce_crossingtaskitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='domicilio_de_enlace',
            field=models.TextField(blank=True, default='', verbose_name='Domicilio de entrega en la frontera'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='linea_de_enlace',
            field=models.CharField(blank=True, default='', help_text='A quien se le deja la carga en la frontera mexicana', max_length=200, verbose_name='Linea transportista de enlace'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='rfc',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RFC'),
        ),
        migrations.CreateModel(
            name='LoadOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('obsoleta', models.BooleanField(default=False)),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_emitidas', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='warehouse.crossingtask')),
            ],
            options={
                'verbose_name': 'Orden de carga',
                'verbose_name_plural': 'Ordenes de carga',
                'ordering': ['-version'],
                'unique_together': {('custom_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LoadOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_order', models.CharField(blank=True, default='', max_length=200)),
                ('bultos', models.PositiveIntegerField(default=0)),
                ('bundle_type', models.CharField(blank=True, default='', max_length=200)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100)),
                ('pedimento', models.CharField(blank=True, default='', max_length=100)),
                ('shipper', models.CharField(blank=True, default='', max_length=200)),
                ('invoice', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones_de_orden', to='warehouse.warehouseoperation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='warehouse.loadorder')),
            ],
            options={
                'verbose_name': 'Renglon de la orden de carga',
                'verbose_name_plural': 'Renglones de la orden de carga',
                'ordering': ['operation__custom_id'],
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('transfer_empresa', models.CharField(blank=True, default='', max_length=200)),
                ('transfer_chofer', models.CharField(blank=True, default='', max_length=200)),
                ('transfer_unidad', models.CharField(blank=True, default='', max_length=100)),
                ('sello', models.CharField(blank=True, default='', max_length=100)),
                ('linea_de_enlace', models.CharField(blank=True, default='', max_length=200)),
                ('domicilio_de_enlace', models.TextField(blank=True, default='')),
                ('destinatario', models.CharField(blank=True, default='', max_length=200)),
                ('destinatario_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('destinatario_domicilio', models.TextField(blank=True, default='')),
                ('con_discrepancia', models.BooleanField(default=False)),
                ('motivo_discrepancia', models.TextField(blank=True, default='')),
                ('diferencia', models.TextField(blank=True, default='', verbose_name='La diferencia exacta')),
                ('bultos_verificados', models.PositiveIntegerField(default=0)),
                ('bultos_de_la_orden', models.PositiveIntegerField(default=0)),
                ('verificada_en', models.DateTimeField(blank=True, null=True)),
                ('emitida_en', models.DateTimeField(auto_now_add=True)),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones', to='warehouse.loadorder')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='warehouse.crossingtask')),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remision',
                'verbose_name_plural': 'Remisiones',
                'ordering': ['-emitida_en'],
            },
        ),
        migrations.CreateModel(
            name='EscaneoDeBulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_bulto', models.PositiveIntegerField()),
                ('fase', models.CharField(choices=[('PREPARACION', 'Picking'), ('CARGA', 'Loading')], default='CARGA', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to='warehouse.warehouseoperation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to='warehouse.crossingtask')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to='warehouse.loadorder')),
            ],
            options={
                'verbose_name': 'Bulto escaneado',
                'verbose_name_plural': 'Bultos escaneados',
                'ordering': ['created_at'],
                'unique_together': {('task', 'operation', 'numero_de_bulto', 'fase')},
            },
        ),
    ]
