# Generated by Django 6.0.7 on 2026-09-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_catalog_domicilio_de_enlace_catalog_linea_de_enlace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossingtaskitem',
            name='bultos',
            field=models.PositiveIntegerField(blank=True, help_text='Vacio = todos', null=True, verbose_name='Bultos que van en este cruce'),
        ),
    ]
