# Generated by Django 6.0.7 on 2026-09-12 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0042_crossingtaskitem_bultos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='en_la_hoja',
            field=models.BooleanField(default=True, verbose_name='Aparece en la hoja'),
        ),
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='quitado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='quitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renglones_quitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
