# Generated by Django 6.0.7 on 2026-09-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0043_renglondeimpuestos_en_la_hoja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='factura_manual',
            field=models.BooleanField(blank=True, null=True, verbose_name='Factura, tecleada'),
        ),
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='pedimento_manual',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Pedimento tecleado'),
        ),
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='status_manual',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Status tecleado'),
        ),
    ]
