# Generated by Django 6.0.7 on 2026-09-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0044_renglondeimpuestos_factura_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renglondeimpuestos',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cerrado por el sistema'),
        ),
    ]
