# Generated by Django 6.0.7 on 2026-09-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0045_renglondeimpuestos_cerrado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='A donde contestan los clientes de esta empresa. Vacio = las respuestas se pierden.', max_length=254, null=True, verbose_name='Correo de respuesta'),
        ),
    ]
