# Generated by Django 6.0.7 on 2026-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0046_tenant_reply_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='provider_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('COMPLAINED', 'Marked as spam')], max_length=10),
        ),
    ]
