# Generated by Django 6.0.7 on 2026-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0047_notificationlog_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('OPERATION_CREATED', 'Operation registered'), ('GOODS_RELEASED', 'Goods released'), ('DOCUMENTS_ADDED', 'Documents added'), ('MANUAL', 'Manual send'), ('INVOICE_SENT', 'Invoice sent'), ('CHAT_MESSAGE', 'Message in the thread'), ('OPERATIONS_REPORT', 'Operations Report'), ('TAX_SHEET', 'Duty estimate sheet'), ('PASSWORD_RESET', 'Password recovery')], max_length=20),
        ),
    ]
