# Generated by Django 6.0.7 on 2026-10-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0050_aviso_de_pedimento_en_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event',
            field=models.CharField(choices=[('OPERATION_CREATED', 'Operation registered'), ('GOODS_RELEASED', 'Goods released'), ('DOCUMENTS_ADDED', 'Documents added'), ('MANUAL', 'Manual send'), ('INVOICE_SENT', 'Invoice sent'), ('CHAT_MESSAGE', 'Message in the thread'), ('OPERATIONS_REPORT', 'Operations Report'), ('TAX_SHEET', 'Duty estimate sheet'), ('PASSWORD_RESET', 'Password recovery'), ('PEDIMENTO_REVIEW', 'Pedimento to review'), ('PEDIMENTO_APPROVED', 'Pedimento approved')], max_length=20),
        ),
    ]
